### ISSUE TITLE
[BUG]: 请求 ChatGPT 服务器时出现问题，请稍后再试 错误信息: AttributeError: 'NoneType' object has no attribute 'new_page'

### ISSUE THREAD

**Issue by jfz520** [A-kirami/nonebot-plugin-chatgpt#100]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

v0.7.3

### 问题描述

请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: AttributeError: 'NoneType' object has no attribute 'new_page'

### 复现步骤

按照教程，我AT机器人问了“1+1”这个问题，然后机器人就回复请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: AttributeError: 'NoneType' object has no attribute 'new_page'
了
![image](https://user-images.githubusercontent.com/89187601/210557322-bd4c043f-0f42-497b-818e-bed75818cbbe.png)

**Comment by PrayerT** [comment]
[#80 (comment)](https://github.com/A-kirami/nonebot-plugin-chatgpt/issues/80)
一样的问题，先看看那个吧

**Comment by jfz520** [comment]
好的，已经解决了，但又出现了新问题：token过期

**Comment by HAKURELING** [comment]
请问一下怎么解决token过期的问题呢

**Comment by Gakki-Loves** [comment]
> 好的，已经解决了，但又出现了新问题：token过期
我也遇到了这个问题，请问您是怎么解决AttributeError: 'NoneType' object has no attribute 'new_page的？

**Comment by Gakki-Loves** [comment]
我也遇到了这个问题，请问您是怎么解决AttributeError: 'NoneType' object has no attribute 'new_page的？

**Comment by sword280** [comment]
请问您是如何解决这个问题的呢？感谢
![image](https://user-images.githubusercontent.com/117010568/213103816-34b0e176-aa5e-4b5d-ad3e-572a275783c5.png)

**Comment by vafyl** [comment]
同问咋个解决

**Comment by Ikaros-521** [comment]
playwright install
https://github.com/A-kirami/nonebot-plugin-chatgpt/issues/80

**Comment by kawaiior** [comment]
楼上给出了答案，playwright install，但是如果是缺少GLIBC_2.18同样会报这个错误，建议根据日志来判断具体情况

**Comment by vafyl** [comment]
我确实是缺少部分GLIBC导致的，根据报错日志缺啥，就解决啥就行了。

**Comment by Passerby1011** [comment]
Running Matcher(type='message', module=nonebot_plugin_chatgpt.utils) failed.
Traceback (most recent call last):
  File "/home/home/chat/bot.py", line 15, in <module>
    nonebot.run()
  File "/home/home/venv/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/home/home/venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/home/home/venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/home/venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/home/venv/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/home/venv/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/home/venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/home/venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/home/home/venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/home/venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/__init__.py", line 66, in ai_chat
    msg = await chat_bot(**session[event]).get_chat_response(text)
  File "/home/home/venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 123, in get_chat_response
    async with self.get_page() as page:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/home/venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 115, in get_page
    page = await self.content.new_page()
AttributeError: 'NoneType' object has no attribute 'new_page'
