### ISSUE TITLE
RuntimeError: Error refreshing session

### ISSUE THREAD

**Issue by DragonEizel** [A-kirami/nonebot-plugin-chatgpt#101]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.2.2

### 问题描述

![Screenshot_2023-01-20-18-18-38-460_com sonelli juicessh](https://user-images.githubusercontent.com/42268998/213680817-c89b53ba-6d36-40f1-aa3f-90632a4a668d.jpg)

从刚部署时就一直出现这个问题，nonebot那边能正常运行，其他插件也正常，但一触发这个插件和自动刷新token时就会出现，我也尝试了其他issue中类似的情况中的方法解决，但仍未解决，更换token也未修复

### 复现步骤

部署nonebot，用nb命令安装本插件，并写入正确的配置信息
从qq向机器人账号发送消息/自动刷新token
后台抛出错误

### 预期行为

正常推送消息到chatgpt并得到回答/正常刷新token

### 实际行为

抛出上图的错误

### 日志信息

[INFO] websockets | connection open                                 01-20 11:25:00 [ERROR] apscheduler | Job "refresh_session (trigger: interval[0:05:00], next run at: 2023-01-20 19:29:59 CST)" raised an exception
Traceback (most recent call last):
  File "/home/linux1/miniconda3/lib/python3.9/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 96, in refresh_session                                               self.authorization = response.json()["accessToken"]
  File "/home/linux1/miniconda3/lib/python3.9/site-packages/httpx/_models.py", line 756, in json                                                                          return jsonlib.loads(self.text, **kwargs)
  File "/home/linux1/miniconda3/lib/python3.9/json/__init__.py", line 346, in loads    return _default_decoder.decode(s)                                                File "/home/linux1/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/linux1/miniconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None               json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linux1/chatGPT/chat4/bot.py", line 46, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/home/linux1/miniconda3/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/home/linux1/miniconda3/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/home/linux1/miniconda3/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
    server.run()                                                                     File "/home/linux1/miniconda3/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/linux1/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/home/linux1/miniconda3/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job                                             retval = await job.func(*job.args, **job.kwargs)
  File "/home/linux1/miniconda3/lib/python3.9/site-packages/nonebot_plugin_chatgpt/__init__.py", line 69, in refresh_session
    await chat_bot.refresh_session()
  File "/home/linux1/miniconda3/lib/python3.9/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 98, in refresh_session
    raise RuntimeError("Error refreshing session") from e
RuntimeError: Error refreshing session

**Comment by xxx-zzl** [comment]
解决了吗
