### ISSUE TITLE
[BUG]: 回复超时，cf cookies获取失败 

### ISSUE THREAD

**Issue by CounterpickToWin** [A-kirami/nonebot-plugin-chatgpt#119]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.7.4

### 问题描述

在服务器（Ubuntu）上env中配置CHATGPT_SESSION_TOKEN登录，加载插件成功后，发送任意消息，后台均报错显示cf cookies获取失败，尝试更新session-token仍然出现同样bug。但是在Windows本地电脑上可以成功运行，并正常返回消息。

### 复现步骤

使用平台：Ubuntu 21
1.env中配置使用CHATGPT_SESSION_TOKEN登录
2.发送任意消息，后台显示cf cookies获取失败

### 预期行为

正常回复信息

### 实际行为

ChatGPT回复已超时

### 日志信息

02-15 20:24:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_chatgpt.utils)
02-15 20:25:11 [ERROR] nonebot_plugin_chatgpt | cf cookies获取失败
02-15 20:25:41 [ERROR] nonebot_plugin_chatgpt | ChatGPT request failed: TimeoutError: Timeout 30000ms exceeded while waiting for event "response"
=========================== logs ===========================
waiting for response https://chat.openai.com/backend-api/conversation
============================================================
Traceback (most recent call last):
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 159, in get_chat_response
    await textarea.fill(prompt)
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 15625, in fill
    await self._impl_obj.fill(
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 198, in fill
    return await self._frame.fill(self._selector, strict=True, **params)
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 528, in fill
    await self._channel.send("fill", locals_to_params(locals()))
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("textarea")
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/root/first/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/root/first/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/root/first/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/__init__.py", line 66, in ai_chat
    msg = await chat_bot(**session[event]).get_chat_response(text)
  File "/root/first/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 151, in get_chat_response
    async with page.expect_response(
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_async_base.py", line 53, in __aexit__
    await self._event.value
  File "/root/first/.venv/lib/python3.10/site-packages/playwright/_impl/_async_base.py", line 34, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded while waiting for event "response"
=========================== logs ===========================
waiting for response https://chat.openai.com/backend-api/conversation
============================================================

**Comment by koking0** [comment]
我也是。
![image](https://user-images.githubusercontent.com/45281765/219369200-16958606-3513-4de6-84e9-162a56f05fab.png)

**Comment by zxczaq001** [comment]
前两天还可以用 昨天开始就这样了

**Comment by CCYellowStar** [comment]
好像官方已经把部分验证你是人类的按钮改成cf人机验证了

**Comment by CCYellowStar** [comment]
![image](https://user-images.githubusercontent.com/47291058/219564950-d188eebc-bd93-4ded-9ae3-d8d802271fdc.png)

**Comment by CCYellowStar** [comment]
呜呜呜找到问题在哪，但是我解决不了，现在有几率检测人类的按钮会被替换成这个，但我不知道怎么用playwright点击这个

**Comment by IvoryTurq** [comment]
> 呜呜呜找到问题在哪，但是我解决不了，现在有几率检测人类的按钮会被替换成这个，但我不知道怎么用playwright点击这个

![image](https://user-images.githubusercontent.com/40100898/219593165-7b84b934-d02d-4da7-a94c-462627219eba.png)
这段代码不就是点击这个的吗？

**Comment by CCYellowStar** [comment]
但他确实没点上

**Comment by CCYellowStar** [comment]
我在元素里找了半天硬是没找到label span是哪个

**Comment by Momo-Tori** [comment]
> 我在元素里找了半天硬是没找到label span是哪个

可以用 `checkbox` 来找吗？

```py
            inputL = page.locator(".checkbox")
            if await inputL.count():
                await inputL.click()
```

我试着加入这个了，还没检查能不能应对这种情况，毕竟不是很经常出现

**Comment by CCYellowStar** [comment]
> > 我在元素里找了半天硬是没找到label span是哪个
> 
> 可以用 `checkbox` 来找吗？
> 
> ```py
>             inputL = page.locator(".checkbox")
>             if await inputL.count():
>                 await inputL.click()
> ```
> 
> 我试着加入这个了，还没检查能不能应对这种情况，毕竟不是很经常出现

这个问题已经解决了，我pr的那个

**Comment by Erlla** [comment]
> > > 我在元素里找了半天硬是没找到label span是哪个
> > 
> > 
> > 可以用 `checkbox` 来找吗？
> > ```python
> >             inputL = page.locator(".checkbox")
> >             if await inputL.count():
> >                 await inputL.click()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我试着加入这个了，还没检查能不能应对这种情况，毕竟不是很经常出现
> 
> 这个问题已经解决了，我pr的那个

更新后还是会显示cf cookies获取失败 = =

**Comment by CCYellowStar** [comment]
> > > > 我在元素里找了半天硬是没找到label span是哪个
> > > 
> > > 
> > > 可以用 `checkbox` 来找吗？
> > > ```python
> > >             inputL = page.locator(".checkbox")
> > >             if await inputL.count():
> > >                 await inputL.click()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我试着加入这个了，还没检查能不能应对这种情况，毕竟不是很经常出现
> > 
> > 
> > 这个问题已经解决了，我pr的那个
> 
> 更新后还是会显示cf cookies获取失败 = =

报错是什么

**Comment by Erlla** [comment]
> > > > > 我在元素里找了半天硬是没找到label span是哪个
> > > > 
> > > > 
> > > > 可以用 `checkbox` 来找吗？
> > > > ```python
> > > >             inputL = page.locator(".checkbox")
> > > >             if await inputL.count():
> > > >                 await inputL.click()
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 我试着加入这个了，还没检查能不能应对这种情况，毕竟不是很经常出现
> > > 
> > > 
> > > 这个问题已经解决了，我pr的那个
> > 
> > 
> > 更新后还是会显示cf cookies获取失败 = =
> 
> 报错是什么

跟上面贴出来的一模一样
![QQ截图20230316214346](https://user-images.githubusercontent.com/49445907/225636117-8f7ca7c1-f85d-4230-847b-fbaae08fb383.png)
![QQ截图20230316214401](https://user-images.githubusercontent.com/49445907/225636137-6e9f4d8d-185b-4c4c-86ef-e5b25fa0a407.png)

**Comment by CCYellowStar** [comment]
你直接访问能进去吗

**Comment by Erlla** [comment]
> 你直接访问能进去吗

能进去，没有任何人机验证啥的

**Comment by CCYellowStar** [comment]
> > 你直接访问能进去吗
> 
> 能进去，没有任何人机验证啥的

你这是什么系统的服务器

**Comment by Erlla** [comment]
> 

群晖上docker ubuntu系统

**Comment by CCYellowStar** [comment]
> > > > 你直接访问能进去吗
> > > 
> > > 
> > > 能进去，没有任何人机验证啥的
> > 
> > 
> > 你这是什么系统的服务器
> 
> 群晖上docker ubuntu系统

chatgpt.py这行改成False，看看他打开浏览器后的情况
![image](https://user-images.githubusercontent.com/47291058/225638236-e07f7816-cb3e-40ce-9d72-abf331978202.png)

**Comment by CCYellowStar** [comment]
playwright install

**Comment by Erlla** [comment]
> 虚拟环境下playwright install
我下午的时候装过了一次，这次没有任何输出
![QQ截图20230316220042](https://user-images.githubusercontent.com/49445907/225642161-e6e16f3f-f227-41ba-8695-14fb522d914e.png)

**Comment by CCYellowStar** [comment]
> > > > > > 你直接访问能进去吗
> > > > > 
> > > > > 
> > > > > 能进去，没有任何人机验证啥的
> > > > 
> > > > 
> > > > 你这是什么系统的服务器
> > > 
> > > 
> > > 群晖上docker ubuntu系统
> > 
> > 
> > chatgpt.py这行改成False，看看他打开浏览器后的情况 ![image](https://user-images.githubusercontent.com/47291058/225638236-e07f7816-cb3e-40ce-9d72-abf331978202.png)
> 
> 出现报错 ![QQ截图20230316220042](https://user-images.githubusercontent.com/49445907/225641139-492d51d3-994a-48a8-aa44-87b03268d095.png) ![QQ截图20230316220030](https://user-images.githubusercontent.com/49445907/225641140-6e789186-2d70-4741-9181-097218fa2847.png)

这张报错的上面有吗

**Comment by Erlla** [comment]
还有

**Comment by CCYellowStar** [comment]
> 还有

看看

**Comment by Erlla** [comment]
> 



> > 还有
> 
> 看看

![QQ截图20230316221319](https://user-images.githubusercontent.com/49445907/225644491-cfa048e7-1687-4558-a012-a7c8710a6dda.png)
![QQ截图20230316221311](https://user-images.githubusercontent.com/49445907/225644505-6ea9889a-2473-4a1e-8b64-727531c1ff80.png)
![QQ截图20230316220042](https://user-images.githubusercontent.com/49445907/225644519-06929303-e52d-4c29-8409-51eaa24645cd.png)

**Comment by Erlla** [comment]
> 

我去研究研究

**Comment by EnchantedHay** [comment]
更新最新版本后仍然出现cf cookies获取失败的情况。
headless设为false后发现是卡在了verify you are human上

**Comment by zxczaq001** [comment]
> > 更新最新版本后仍然出现cf cookies获取失败的情况。
> > headless设为false后发现是卡在了verify you are human上
> > 甚至在please stand by check了一下我的browser之后连verify的按钮都不给我了
> 
> 能手动点掉吗

![image](https://user-images.githubusercontent.com/104310573/227127914-348fcf5b-1871-4ee2-961c-6233b2eb61f9.png)
我现在是这个报错好多天了

**Comment by EnchantedHay** [comment]
> > 更新最新版本后仍然出现cf cookies获取失败的情况。
> > headless设为false后发现是卡在了verify you are human上
> > 甚至在please stand by check了一下我的browser之后连verify的按钮都不给我了
> 
> 能手动点掉吗

手动点掉是可以的，但仍然不会收到回复，仍会显示超时，浏览器页面显示对话框内会有QQ那一端输入的文字，但并没有执行回复，回车执行回复后QQ那一端也不会收到回复内容。

**Comment by zmq175** [comment]
我这边运行报错
![image](https://user-images.githubusercontent.com/9747443/227744117-8d368930-3913-4a22-b5aa-b16455dda17f.png)

**Comment by modongfox** [comment]
我这边也报这个错误，按照上面的提示修改还是报cf cookies获取失败
设备：ubuntu20.04，与该问题描述基本一致
![错误代码1](https://user-images.githubusercontent.com/61340411/229272045-ac214578-109b-4f2e-aeae-c0555678e784.png)
![错误代码2](https://user-images.githubusercontent.com/61340411/229272048-c2e4224b-dfd1-4ce1-8165-8d1012a15e7e.png)
![错误代码3](https://user-images.githubusercontent.com/61340411/229272053-e3d9cd51-4dd4-4fcb-b956-973651558d93.png)
