### ISSUE TITLE
[BUG]: [ERROR]uvicorn | Application startup failed. Exiting.

### ISSUE THREAD

**Issue by hatoriss** [A-kirami/nonebot-plugin-chatgpt#124]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.7.4

### 问题描述

同issue#90，插件加载成功但uvicorn启动失败导致退出，不加载本插件则可成功启动机器人。

### 复现步骤

按照#90的解决方法，在dev与env中都写入了相关配置，但仍报错，并出现问题如上。

### 预期行为

正常运行

### 实际行为

启动失败

### 日志信息

Succeeded to import "nonebot_plugin_naturel_gpt"
02-21 18:37:50 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
02-21 18:37:50 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
02-21 18:37:50 [WARNING] nonebot | Duplicated prefix rule "/导出会话"
02-21 18:37:50 [WARNING] nonebot | Duplicated prefix rule "/切换会话"
02-21 18:37:50 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_chatgpt"
02-21 18:37:50 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
02-21 18:37:50 [SUCCESS] nonebot | Running NoneBot...
02-21 18:37:50 [INFO] uvicorn | Started server process [27854]
02-21 18:37:50 [INFO] uvicorn | Waiting for application startup.
02-21 18:37:50 [INFO] nonebot_plugin_apscheduler | Scheduler Started
02-21 18:37:51 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
02-21 18:37:51 [INFO] nonebot_plugin_htmlrender | 使用镜像源进行下载
02-21 18:37:51 [INFO] nonebot_plugin_htmlrender | 正在安装 chromium
02-21 18:37:51 [INFO] nonebot_plugin_htmlrender | 正在安装依赖
sh: playwright: command not found
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
02-21 18:37:51 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
02-21 18:37:51 [ERROR] uvicorn | Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 38, in init
    _browser = await launch_browser(**kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 56, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 14340, in launch
    await self._impl_obj.launch(
  File "/usr/local/python3/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/usr/local/python3/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 44, in send
 return await self._connection.wrap_api_call(
  File "/usr/local/python3/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/usr/local/python3/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libatspi.so.0                                    ║
║     libXcomposite.so.1                               ║
║     libXdamage.so.1                                  ║
║     libXext.so.6                                     ║
║     libXfixes.so.3                                   ║
║     libXrandr.so.2                                   ║
║     libgbm.so.1                                      ║
║     libxkbcommon.so.0                                ║
║     libpango-1.0.so.0                                ║
║     libcairo.so.2                                    ║
╚══════════════════════════════════════════════════════╝

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/python3/lib/python3.9/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/usr/local/python3/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot_plugin_htmlrender/__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 60, in get_browser
    return _browser if _browser and _browser.is_connected() else await init(**kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 41, in init
    _browser = await launch_browser(**kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 56, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 14340, in launch
    await self._impl_obj.launch(
  File "/usr/local/python3/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/usr/local/python3/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/python3/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/usr/local/python3/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libatspi.so.0                                    ║
║     libXcomposite.so.1                               ║
║     libXdamage.so.1                                  ║
║     libXext.so.6                                     ║
║     libXfixes.so.3                                   ║
║     libXrandr.so.2                                   ║
║     libgbm.so.1                                      ║
║     libxkbcommon.so.0                                ║
║     libpango-1.0.so.0                                ║
║     libcairo.so.2                                    ║
╚══════════════════════════════════════════════════════╝

02-21 18:37:51 [ERROR] uvicorn | Application startup failed. Exiting.
[root@VM-4-6-centos watarulinux]#

### 额外补充

在这个机器人中存在其他gpt插件，是否存在冲突可能。

**Comment by lgc2333** [comment]
缺库了 自己按照提示装一下

**Comment by adobj** [comment]
**Ubuntu 使用 apt：**
`apt update && apt install -y locales locales-all fonts-noto libnss3-dev libxss1 libasound2 libxrandr2 libatk1.0-0 libgtk-3-0 libgbm-dev libxshmfence1`
然后设置 ENV local
`LANG zh_CN.UTF-8`
`LANGUAGE zh_CN.UTF-8`
`LC_ALL zh_CN.UTF-8`

**CentOS 使用 yum：**
`dnf install -y alsa-lib at-spi2-atk at-spi2-core atk cairo cups-libs dbus-libs expat flac-libs gdk-pixbuf2 glib2 glibc gtk3 libX11 libXcomposite libXdamage libXext libXfixes libXrandr libXtst libcanberra-gtk3 libdrm libgcc libstdc++ libxcb libxkbcommon libxshmfence libxslt mesa-libgbm nspr nss nss-util pango policycoreutils policycoreutils-python-utils zlib cairo-gobject centos-indexhtml dbus-glib fontconfig freetype gtk2 libXcursor libXi libXrender libXt liberation-fonts-common liberation-sans-fonts libffi mozilla-filesystem p11-kit-trust pipewire-libs harfbuzz-icu libglvnd-glx libglvnd-egl libnotify opus woff2 gstreamer1-plugins-base gstreamer1-plugins-bad-free openjpeg2 libwebp enchant libsecret hyphen libglvnd-gles`
