### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by sherlockHlb** [A-kirami/nonebot-plugin-chatgpt#130]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

2023年2月25日

### 问题描述

使用内置浏览器无法访问https://chat.openai.com/chat.返回错误1020或者
Secure Connection Failed

An error occurred during a connection to chat.openai.com. PR_END_OF_FILE_ERROR

Error code: PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
网络正常,使用edge浏览器可以正常浏览网站

### 复现步骤

1.设置debug网页弹窗
测试访问,
返回Secure Connection Failed

An error occurred during a connection to chat.openai.com. PR_END_OF_FILE_ERROR

Error code: PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

机器人回复ChatGPT 目前无法回复您的问题。
Error: NS_ERROR_NET_INTERRUPT
=========================== logs ===========================
navigating to "https://chat.openai.com/chat", waiting until "load"
============================================================

**Comment by sherlockHlb** [comment]
02-25 00:09:48 [ERROR] nonebot_plugin_chatgpt | ChatGPT request failed: Error: NS_ERROR_NET_INTERRUPT
=========================== logs ===========================
navigating to "https://chat.openai.com/chat", waiting until "load"
============================================================
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\bot.py", line 17, in <module>
    nonebot.run()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1919, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_plugin_chatgpt\__init__.py", line 66, in ai_chat
    msg = await chat_bot(**session[event]).get_chat_response(text)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 123, in get_chat_response
    async with self.get_page() as page:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 118, in get_page
    await page.goto("https://chat.openai.com/chat")
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\playwright\async_api\_generated.py", line 9135, in goto
    await self._impl_obj.goto(
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\playwright\_impl\_page.py", line 491, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: NS_ERROR_NET_INTERRUPT
=========================== logs ===========================
navigating to "https://chat.openai.com/chat", waiting until "load"
============================================================
02-25 00:09:48 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_chatgpt.utils) running complete
