### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by ks-EKY** [A-kirami/nonebot-plugin-chatgpt#138]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

nb商店的版本

### 问题描述

也开了系统代理，配置了env的token和FASTAPI_RELOAD = false，有时候运行说 #119 类似这个，有时候又会显示下面我发的日志，bot回复的是chatgpt目前无法回复您的问题。可能的原因是同时提问过多，问题过于复杂等。或者ChatGPT回复已超时。

### 复现步骤

每次都有

### 预期行为

正常运行

### 实际行为

日志报错

### 日志信息

03-26 06:38:49 [SUCCESS] nonebot | OneBot V11 1017549025 | [message.group.normal]: Message -1147473740 from 3184165835@[群:983738958] '[at:qq=1017549025] 修不好'
03-26 06:38:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
03-26 06:38:49 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
03-26 06:38:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_chatgpt.utils)
03-26 06:39:13 [ERROR] nonebot_plugin_chatgpt | ChatGPT request failed: Error: Execution context was destroyed, most likely because of a navigation
=========================== logs ===========================
  checking visibility of locator("text=OpenAI Discord")
============================================================
Traceback (most recent call last):
  File "E:\nonebot2\nonebot2-oneclick-win\bot.py", line 98, in <module>
    nonebot.run()
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot_plugin_chatgpt\__init__.py", line 66, in ai_chat
    msg = await chat_bot(**session[event]).get_chat_response(text)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 126, in get_chat_response
    await self.get_cf_cookies(page)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 240, in get_cf_cookies
    if await cf.is_visible():
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\async_api\_generated.py", line 16855, in is_visible
    return mapping.from_maybe_impl(await self._impl_obj.is_visible(timeout=timeout))
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_locator.py", line 450, in is_visible
    return await self._frame.is_visible(
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_frame.py", line 353, in is_visible
    return await self._channel.send("isVisible", locals_to_params(locals()))
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation
=========================== logs ===========================
  checking visibility of locator("text=OpenAI Discord")
============================================================

### 额外补充

无

**Comment by QNLanYang** [comment]
这边的建议是把playwright的headless设置成false看看浏览器界面卡在哪里了，感觉像是有初次弹窗卡住了之类的，另外发送按钮的样式也改了， #137 。

**Comment by ks-EKY** [comment]
卡在输上内容没有发送的地方了

**Comment by ks-EKY** [comment]
日志报错是cf cookies获取失败，然后是卡在了输入的地方，在日志的地方按下回车浏览器输入框才会显示输入的内容，然后就卡在输入框有字不发送的地方了，之后bot回复的是chatGPT回复超时，日志报错  ChatGPT request failed: TimeoutError: Timeout 30000ms exceeded while waiting for event "response"
=========================== logs ===========================
waiting for response https://chat.openai.com/backend-api/conversation
============================================================
Traceback (most recent call last):
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 162, in get_chat_response
    if await botton.is_enabled():
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\async_api\_generated.py", line 16803, in is_enabled
    return mapping.from_maybe_impl(await self._impl_obj.is_enabled(timeout=timeout))
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_locator.py", line 434, in is_enabled
    return await self._frame.is_editable(
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_frame.py", line 338, in is_editable
    return await self._channel.send("isEditable", locals_to_params(locals()))
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("button[class=\"absolute p-1 rounded-md text-gray-500 bottom-1.5 md:bottom-2.5 hover:bg-gray-100 dark:hover:text-gray-400 dark:hover:bg-gray-900 disabled:hover:bg-transparent dark:disabled:hover:bg-transparent right-1 md:right-2\"]")
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\nonebot2\nonebot2-oneclick-win\bot.py", line 99, in <module>
    nonebot.run()
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot_plugin_chatgpt\__init__.py", line 66, in ai_chat
    msg = await chat_bot(**session[event]).get_chat_response(text)
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 153, in get_chat_response
    async with page.expect_response(
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_async_base.py", line 53, in __aexit__
    await self._event.value
  File "E:\nonebot2\nonebot2-oneclick-win\venv\virtualenvs\nb2-oneclick-CTxwZjGP-py3.10\lib\site-packages\playwright\_impl\_async_base.py", line 34, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded while waiting for event "response"
=========================== logs ===========================
waiting for response https://chat.openai.com/backend-api/conversation
============================================================
