### ISSUE TITLE
[BUG]: 频繁请求可能会导致 httpcore.ReadTimeout

### ISSUE THREAD

**Issue by cvb011** [A-kirami/nonebot-plugin-chatgpt#2]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.1.1

### 问题描述

在以大约数秒(<10)的速度调用该插件一段时间之后，会出现 httpcore.ReadTimeout 报错

### 复现步骤

在以大约数秒(<10)的速度调用该插件

### 日志信息

```
12-05 14:05:05 [ERROR] nonebot | Running Matcher(type='message', module=plugins.nonebot_plugin_chatgpt) failed.
Traceback (most recent call last):

  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
    result = func(*args)
             │     └ (65536,)
             └ <bound method SSLObject.read of <ssl.SSLObject object at 0x7fe3fd8c7280>>
  File "/usr/lib/python3.10/ssl.py", line 917, in read
    v = self._sslobj.read(len)
        │    │       │    └ 65536
        │    │       └ <method 'read' of '_ssl._SSLSocket' objects>
        │    └ <_ssl._SSLSocket object at 0x7fe422088200>
        └ <ssl.SSLObject object at 0x7fe3fd8c7280>

ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2548)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 33, in read
    return await self._stream.receive(max_bytes=max_bytes)
                 │    │       │                 └ 65536
                 │    │       └ <function TLSStream.receive at 0x7fe421ef3370>
                 │    └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x7fe3fd8c6290>, standard_compatible=False, _ssl_...
                 └ <httpcore.backends.asyncio.AsyncIOStream object at 0x7fe3fd8c69e0>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
                 │    │                      │    │           │     └ 65536
                 │    │                      │    │           └ <function SSLObject.read at 0x7fe424590310>
                 │    │                      │    └ <ssl.SSLObject object at 0x7fe3fd8c7280>
                 │    │                      └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x7fe3fd8c6290>, standard_compatible=False, _ssl_...
                 │    └ <function TLSStream._call_sslobject_method at 0x7fe421ef31c0>
                 └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x7fe3fd8c6290>, standard_compatible=False, _ssl_...
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
                 │    │                └ <function SocketStream.receive at 0x7fe401d00d30>
                 │    └ <anyio._backends._asyncio.SocketStream object at 0x7fe3fd8c6290>
                 └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x7fe3fd8c6290>, standard_compatible=False, _ssl_...
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
          │    │         │          └ <function Event.wait at 0x7fe423ec2a70>
          │    │         └ <asyncio.locks.Event object at 0x7fe3fd8c5b70 [set]>
          │    └ <anyio._backends._asyncio.StreamProtocol object at 0x7fe3fd8c4730>
          └ <anyio._backends._asyncio.SocketStream object at 0x7fe3fd8c6290>
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
          └ <Future cancelled>

asyncio.exceptions.CancelledError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 31, in read
    with anyio.fail_after(timeout):
         │     │          └ 10
         │     └ <function fail_after at 0x7fe421ebd900>
         └ <module 'anyio' from '/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/anyio/...
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError

TimeoutError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'POST']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x7fe421a28af0>
                 │    └ <httpcore.AsyncConnectionPool object at 0x7fe3fd8c7d90>
                 └ <httpx.AsyncHTTPTransport object at 0x7fe3fd8c6b60>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
                     │          │                    └ <Request [b'POST']>
                     │          └ <function AsyncHTTPConnection.handle_async_request at 0x7fe421a1bd90>
                     └ <AsyncHTTPConnection ['https://chat.openai.com:443', HTTP/1.1, CLOSED, Request Count: 1]>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
                 │    │           │                    └ <Request [b'POST']>
                 │    │           └ <function AsyncHTTP11Connection.handle_async_request at 0x7fe421a1a9e0>
                 │    └ <AsyncHTTP11Connection ['https://chat.openai.com:443', CLOSED, Request Count: 1]>
                 └ <AsyncHTTPConnection ['https://chat.openai.com:443', HTTP/1.1, CLOSED, Request Count: 1]>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 105, in handle_async_request
    raise exc
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 84, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
              │    │                           └ {'request': <Request [b'POST']>}
              │    └ <function AsyncHTTP11Connection._receive_response_headers at 0x7fe421a1b400>
              └ <AsyncHTTP11Connection ['https://chat.openai.com:443', CLOSED, Request Count: 1]>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 148, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
                  │    │                      └ 10
                  │    └ <function AsyncHTTP11Connection._receive_event at 0x7fe421a1b520>
                  └ <AsyncHTTP11Connection ['https://chat.openai.com:443', CLOSED, Request Count: 1]>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/_async/http11.py", line 177, in _receive_event
    data = await self._network_stream.read(
                 │    │               └ <function AsyncIOStream.read at 0x7fe401d03520>
                 │    └ <httpcore.backends.asyncio.AsyncIOStream object at 0x7fe3fd8c69e0>
                 └ <AsyncHTTP11Connection ['https://chat.openai.com:443', CLOSED, Request Count: 1]>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 30, in read
    with map_exceptions(exc_map):
         │              └ {<class 'TimeoutError'>: <class 'httpcore.ReadTimeout'>, <class 'anyio.BrokenResourceError'>: <class 'httpcore.ReadError'>}
         └ <function map_exceptions at 0x7fe4219f0af0>
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x7fe402030080>
    │    │   │     │    └ TimeoutError()
    │    │   │     └ <class 'TimeoutError'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_exceptions at 0x7fe3ff9feb20>
    └ <contextlib._GeneratorContextManager object at 0x7fe3fc3f2e60>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
          └ <class 'httpcore.ReadTimeout'>

httpcore.ReadTimeout


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/jason/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7fe422e85f30>
    └ <module 'nonebot' from '/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/none...

  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7fe42471d090>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7fe421e3f640>
    └ <module 'uvicorn' from '/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/uvic...
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 576, in run
    server.run()
    │      └ <function Server.run at 0x7fe421e3f7f0>
    └ <uvicorn.server.Server object at 0x7fe4022d35b0>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fe421e3f880>
           │       │   └ <uvicorn.server.Server object at 0x7fe4022d35b0>
           │       └ <function run at 0x7fe4244dbc70>
           └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fe4022f63b0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fe422ea4c10>: <Task finished name='Task-148474' coro=<_command() done, defined at /home/jason/.cach...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe3fc4cdc30>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │            │        │    └ GroupMessageEvent(time=1670249093, self_id=2037909602, post_type='message', sub_type='normal', user_id=[qq_id], message_ty...
          │            │        └ Bot(type='OneBot V11', self_id='2037909602')
          │            └ Matcher(type='message', module=plugins.nonebot_plugin_chatgpt)
          └ <function _run_matcher at 0x7fe422da2200>
> File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fe422ea4c10>: <Task finished name='Task-148474' coro=<_command() done, defined at /home/jason/.cach...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe3fc4cdc30>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │       │   │    └ GroupMessageEvent(time=1670249093, self_id=2037909602, post_type='message', sub_type='normal', user_id=[qq_id], message_ty...
          │       │   └ Bot(type='OneBot V11', self_id='2037909602')
          │       └ <function Matcher.run at 0x7fe422ea4790>
          └ Matcher(type='message', module=plugins.nonebot_plugin_chatgpt)
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fe422ea4c10>: <Task finished name='Task-148474' coro=<_command() done, defined at /home/jason/.cach...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fe3fc4cdc30>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │    │          │    └ GroupMessageEvent(time=1670249093, self_id=2037909602, post_type='message', sub_type='normal', user_id=[qq_id], message_ty...
          │    │          └ Bot(type='OneBot V11', self_id='2037909602')
          │    └ <function Matcher.simple_run at 0x7fe422ea4700>
          └ Matcher(type='message', module=plugins.nonebot_plugin_chatgpt)
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 688, in simple_run
    await handler(
          └ Dependent(call=_)
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'event': GroupMessageEvent(time=1670249093, self_id=2037909602, post_type='message', sub_type='normal', user_id=[qq_id], ...
                 │    │             │         │    │    └ <function _ at 0x7fe40350f400>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7fe4247945e0>

  File "/home/jason/zhenxun_bot/plugins/nonebot_plugin_chatgpt/__init__.py", line 44, in _
    msg = await chat_bot(**session[event.user_id]).get_chat_response(text)
                │          │       │     │                           └ '如何评价原神抄袭塞尔达'
                │          │       │     └ [qq_id]
                │          │       └ GroupMessageEvent(time=1670249093, self_id=2037909602, post_type='message', sub_type='normal', user_id=[qq_id], message_ty...
                │          └ defaultdict(<class 'dict'>, {[qq_id]: {'conversation_id': 'ae0dadb7-56b9-4d44-8be9-484e5dc1d123', 'parent_id': 'da634643-a...
                └ <plugins.nonebot_plugin_chatgpt.chatgpt.Chatbot object at 0x7fe403575a80>

  File "/home/jason/zhenxun_bot/plugins/nonebot_plugin_chatgpt/chatgpt.py", line 65, in get_chat_response
    response = await client.post(
                     │      └ <function AsyncClient.post at 0x7fe421849510>
                     └ <httpx.AsyncClient object at 0x7fe401dbe590>

  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1842, in post
    return await self.request(
                 │    └ <function AsyncClient.request at 0x7fe421848f70>
                 └ <httpx.AsyncClient object at 0x7fe401dbe590>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x7fe421af2a70>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x7fe421af2a70>
                 │    │    └ <Request('POST', 'https://chat.openai.com/backend-api/conversation')>
                 │    └ <function AsyncClient.send at 0x7fe421849120>
                 └ <httpx.AsyncClient object at 0x7fe401dbe590>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x7fe4218491b0>
                     └ <httpx.AsyncClient object at 0x7fe401dbe590>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x7fe421849240>
                     └ <httpx.AsyncClient object at 0x7fe401dbe590>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('POST', 'https://chat.openai.com/backend-api/conversation')>
                     │    └ <function AsyncClient._send_single_request at 0x7fe4218492d0>
                     └ <httpx.AsyncClient object at 0x7fe401dbe590>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('POST', 'https://chat.openai.com/backend-api/conversation')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x7fe421a2a830>
                     └ <httpx.AsyncHTTPTransport object at 0x7fe3fd8c6b60>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
         └ <function map_httpcore_exceptions at 0x7fe4219e3370>
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x7fe401ebf780>
    │    │   │     │    └ ReadTimeout(TimeoutError())
    │    │   │     └ <class 'httpcore.ReadTimeout'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_httpcore_exceptions at 0x7fe4221a3f40>
    └ <contextlib._GeneratorContextManager object at 0x7fe3fd8c7d60>
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ ''
          └ <class 'httpx.ReadTimeout'>

httpx.ReadTimeout
```

### 额外补充

抱歉没有控制台截图

**Comment by koking0** [comment]
+1，我也遇到了

**Comment by yzyyz1387** [comment]
同，没挂代理跑了几次就这样，挂代理后恢复正常，然后用了几次又这样了，之前看到[rawandahmad698/PyChatGPT](https://github.com/rawandahmad698/PyChatGPT#the-whole-process)有对鉴权和防机器人的相关叙述，应该是openai那边验证比较严格 🤙

**Comment by ReiRzior** [comment]
+1,也出现这个问题了

**Comment by satisl** [comment]
+1,出现这种问题

**Comment by rickly233** [comment]
+1,出现这种问题

**Comment by Z735803792** [comment]
+1，挂代理一会也出这个问题

**Comment by Sincejunly** [comment]
我不一样，我是这个样子
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)
以及 httpx.ReadTimeout 挂代理也没用

**Comment by APeng215** [comment]
这是因为chatGPT那边响应太慢，延时超过10s，导致插件以为它超时了。我把CHATGPT_TIMEOUT属性配置成30，就不会出现这个问题了

**Comment by Hustoking** [comment]
当机器人说出：“请求过多，请放慢速度时” 应该怎么做呢？

**Comment by A-kirami** [comment]
> 当机器人说出：“请求过多，请放慢速度时” 应该怎么做呢？

答案是放慢速度或者等一段时间再试

**Comment by ReiRzior** [comment]
嗯，我也解决了，我设成两分钟，再没出错过

A_Peng215 ***@***.***> 于 2022年12月8日周四 19:22写道：
