### ISSUE TITLE
[BUG]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by FlashKiana** [A-kirami/nonebot-plugin-chatgpt#6]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

v0.2.0 fe9a462

### 问题描述

命令成触发几次后，之后就再也没理我了，后台错误截图
![QQ截图20221206133050](https://user-images.githubusercontent.com/24948734/205825191-9a8e9796-ac19-46e1-aea0-b20c965ce6d7.png)

### 复现步骤

首先发送命令
然后没有回复
结果报错

**Comment by Nova-Noir** [comment]
see #7

**Comment by FlashKiana** [comment]
12-06 14:11:25 [SUCCESS] nonebot | OneBot V11 206842378 | [message.group.normal]: Message -817248246 from 393429529@[群:608389811] "派蒙你好"
12-06 14:11:25 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_chatgpt)
12-06 14:11:25 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_chatgpt) running complete
12-06 14:11:25 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_chatgpt) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 92, in refresh_session
    self.authorization = response.json()["accessToken"]
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\httpx\_models.py", line 751, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot_plugin_chatgpt\__init__.py", line 50, in ai_chat
    msg = await chat_bot(**session[session_id]).get_chat_response(text)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 64, in get_chat_response
    await self.refresh_session()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\paimon-h7_1FjhX-py3.10\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 94, in refresh_session
    raise RuntimeError("Error refreshing session") from e
RuntimeError: Error refreshing session

最新的0.2.1还是这个问题

**Comment by FlashKiana** [comment]
![image](https://user-images.githubusercontent.com/24948734/205835493-aeca7443-8859-4107-b8fe-bda1c92bfa22.png)
这是我的配置截图和这个有关吗？

**Comment by A-kirami** [comment]
> ![image](https://user-images.githubusercontent.com/24948734/205835493-aeca7443-8859-4107-b8fe-bda1c92bfa22.png) 这是我的配置截图和这个有关吗？

你的token是只有这么长还是没换行

**Comment by FlashKiana** [comment]
eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Yamth_Co8mHcTutK.DPg6zSoCk7D1MJ23ld437cCUjWWqjo7xgGpAwmnN-Dp1pf8b2Kb3RZwBpcKcj3TmT_nJZrLusH_hG3i_0l27YjHoaYY7AcprPqY9dRrTBudnylwxAQ0Hv6YqJy-2dRiY7RvKd-PLzcNiTgsoB74vB0RFs89t8n7RZiQ1BA0eOBgiYF4ffbtqgpawiR80f4Mw_-KTzwjP_Xj9kYpFOBMkQ6ALikPjxYlielJNLxdtT8UlNktGnfpSwQyPrLPPgch41ma7YcNiwFLyi8C5vjs5GoSDaEVvQiYcwZa51lnpHaO649icGN9s0j6llDigJVnGDxwiCeTVzoRTgUL4TUs2eTX7uND-H2DKVIjOh7ziQlb7GUQVCwlCox7LUzLSaXYAeRwy6ZfnDy5xn0s2wMJG00ToAIyFJXjoQNncz3cSvPhg7gbuA-Ht5NWpn8NQuhokxv00hVAJY5YhOim9AQxM2xDhQ5DMWHvEhY8nzRYffThyXzy0wcgFpJ0kWBFtoj6G0IZt65s2nVFlnb7McgocEl6qxxCKz-APYOmI0wEv3EMAbfQ0dWuziKvl-mWPFcYQgpmw5SD5_79buxACJJnO6zajzRsJcmOsxZ18Dc0cdhKoQtnt9NSR4-vVJnIyHJWCin3dGJE9GkUel_UwLXgsfqq10q3-4eLsfGwtiwG95S3lvJB16dG53hZOoz19yXCmz7ACZ7tKZd3VGbUM8Ab8QKoa978FKWuGkB_eT77lUV9SWjQRAE_ZiHUW0yS4T-GrWi4fyz6dSOCla_-Z0gXT6r1ikERmSGIp4somY0w2jDJpGf_a2MAlyibZ2sY22eOakR8OhCkl0c1pQdhEny9j_STJBpbmcOVwHmZG48Uj-WMvxBf9kp5o6K9PuQMGTXfaiKyAylr8H2UIO1ftEREF4WMlpl2o5KAlUUuepqiqH92E9R6fJltZ06ZYiKQIGyhwFC8uSDTcGSocUvK_1ZIHSyd8TgemHp0ek3CwcRTSWLPIdcR8R96J2K6KMdGu8MCHlLmr48qnE2iN7bmfEr-PdrLK6zrldhjPN_NZHFsXLEh2PvKBDL8vI5JSHni75REGvwmuqRWMRXLabHkDWVsWjA5TIhAz2u4wj-8pZP9PL3WcpYr5oEwus54XpENUDXsVC-57wqmzpjfYZg18y1AG5BcKsIsH1r19IRR_QE4r-8ocFE2Nt5Bn5k3ajx9mxlXRCm8JbrQqMLUZzr_q2unffGJ2mIIKa60mZ2rd2nrZ9V4uS5ec1JZO_LGAx_-3TVircYk1Ek01sOwcBcP6rvWnTGr67qfpv4Pi9vZMDhAC5AqZBEN396UNKwmoDERvOVpvfE5ejsqlvpT2P-eHxXHRxKFTcS0fIXIP7dSdCPkGbWGynpzLYmP0D73-9DDwVb1Tqm71yLD4Er-f0N59aMA6m2DFRMxK1RheM_wg5bgBYH8Ai4H5f1LVUaFgkvjFOwLRWAHp0BxhHXew5HFVIGg_vlJU6N1m9RVB3ZsNZpncZ1_APUz0Bdvxbc4Nc8bzc_FF-oGlMiTgtwv-LK9CEVloFX4NAKAEdtj-Ey7702ztIHa7Om1MFdzQIf-kqn2cUSRvGrOFZ73UR4HWeKh1rvM8wnD5__d6g37sN5zzf0Qtcp4xfW-DZvPaIwHWt4oEs6hGkMBHc3BBe2eZyrtpbcTeTx9clOvnNzBuJxi2FuyDp5mdSQcGanEnqyNB2m9hxs0uemMEBvtmoew7lMYr70cEGpxqFOKkFa8H62QTmgEe7Q-nQO_1TBe_jj_tDkg7fBR9O7GVlC5_AWVDL66xSyJDwps7KKdn_zCA08nOR-E_HI3O31r7nDKegk_nTeK1wphiLrzjpp3fUghpqfc9D5zyC8E1kZ4Uk9Cf_Fiwoxcg5G28dP-zVeY6UsadeLdOJh0GZWS5nhCc8fWfMJDac49mnLq0A0GGjdheebKYfebG2yEXdXSbvaHTIUUsMuhH-GTGAE8oLBh9aNrRlGIXWRMp5f6Bx287lTeVG1yTVnYk-kas7Z64F6rJsS5EZriZzYDXZTyFkZziy_6jYW7UuvnumqhGu_ODNr9WLEwEgy0TLlNMy0MvnpW0mBjEeKaFb1TIDORpdg5oMIi5W1N3TBUIvNtycto9FYWDyw.n0VgaEvoY33AD8B157CWgA

**Comment by FlashKiana** [comment]
全部这么长没换行

**Comment by A-kirami** [comment]
> 全部这么长没换行

尝试更换一下token看看

**Comment by FlashKiana** [comment]
![image](https://user-images.githubusercontent.com/24948734/205838134-bfc88498-9dfc-4699-a783-b6a528ca0387.png)
重新登陆获取还是同样的错误，而且我发现这一栏的值会一直变
![image](https://user-images.githubusercontent.com/24948734/205838381-16281af7-ef1f-48b1-bd80-24c850bd6431.png)
我打字的功夫他就变了，会不会和这个有关
![image](https://user-images.githubusercontent.com/24948734/205838510-8fe58364-daf7-4bcf-9c73-f35b4e08ec4b.png)

**Comment by Nova-Noir** [comment]
在 https://github.com/A-kirami/nonebot-plugin-chatgpt/blob/28bda8d28895d0500308d4c68f7761c36ec6d205/nonebot_plugin_chatgpt/chatgpt.py#L89 处，为请求添加 `header` 即可

```python
response = await client.get("https://chat.openai.com/api/auth/session",
             headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
                                    "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"})
```

**Comment by FlashKiana** [comment]
> ```python
> response = await client.get("https://chat.openai.com/api/auth/session",
>              headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
>                                     "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"})
> ```



> 在
> 
> https://github.com/A-kirami/nonebot-plugin-chatgpt/blob/28bda8d28895d0500308d4c68f7761c36ec6d205/nonebot_plugin_chatgpt/chatgpt.py#L89
> 
> 处，为请求添加 `header` 即可
> ```python
> response = await client.get("https://chat.openai.com/api/auth/session",
>              headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
>                                     "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"})
> ```

现在可以了

**Comment by A-kirami** [comment]
尝试更换0.2.2版本

**Comment by FlashKiana** [comment]
> 在
> 
> https://github.com/A-kirami/nonebot-plugin-chatgpt/blob/28bda8d28895d0500308d4c68f7761c36ec6d205/nonebot_plugin_chatgpt/chatgpt.py#L89
> 
> 处，为请求添加 `header` 即可
> ```python
> response = await client.get("https://chat.openai.com/api/auth/session",
>              headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
>                                     "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"})
> ```

这个方法可以 谢谢各位大佬

**Comment by FlashKiana** [comment]
> 尝试更换0.2.2版本

可以啦，谢谢
