### ISSUE TITLE
[BUG]: RuntimeError: Cannot load plugin "nonebot_plugin_htmlrender"!

### ISSUE THREAD

**Issue by LSGLSH** [A-kirami/nonebot-plugin-chatgpt#61]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

当前最新版本

### 问题描述

无法读取 "nonebot_plugin_htmlrender"!

### 复现步骤

和之前一样手动覆盖和安装，出现启动报错。

### 日志信息

、Traceback (most recent call last):
  File "/home/bot/zhenxun_bot/bot.py", line 16, in <module>
    nonebot.load_plugins("my_plugins")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_chatgpt/__init__.py", line 22, in <module>
    require("nonebot_plugin_htmlrender")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 165, in require
    plugin = load_plugin(name)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 155, in load_plugin
    raise RuntimeError(
RuntimeError: Module nonebot_plugin_htmlrender is not loaded as a plugin! Make sure not to import it before loading.
12-14 00:08:44 [ERROR] nonebot | Failed to import "nonebot_plugin_chatgpt"
Traceback (most recent call last):
  File "/home/bot/zhenxun_bot/bot.py", line 16, in <module>
    nonebot.load_plugins("my_plugins")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/bot/zhenxun_bot/my_plugins/nonebot_plugin_chatgpt/__init__.py", line 22, in <module>
    require("nonebot_plugin_htmlrender")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-lAGE7ajM-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 167, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_htmlrender"!

**Comment by LSGLSH** [comment]
可以的话我留个联系方式QQ2368343278

**Comment by Siota02** [comment]
缺少依赖，cmd或者powershell中运行pip install nonebot_plugin_htmlrender

**Comment by LSGLSH** [comment]
> 缺少依赖，cmd或者powershell中运行pip install nonebot_plugin_htmlrender

已确定我是安装过这个依赖，但是他就是读取不到

**Comment by Siota02** [comment]
> > 缺少依赖，cmd或powershell中运行pip install nonebot_plugin_htmlrender
> 
> 已经确定我是安装过这个依赖的，但是他就是读取不到

htmlrender因为语法问题，你可以尝试升级到python10及以上

**Comment by caiwj13** [comment]
更新后遇到相同的问题。python 3.10.4, nonebot-plugin-htmlrender 0.2.0.1

**Comment by Siota02** [comment]
> 更新后遇到相同的问题。python 3.10.4, nonebot-plugin-htmlrender 0.2.0.1

确保是否安装依赖齐全执行以下操作，如是更新python版本需对原版本依赖重新安装
1.可以尝试clone htmlender仓
2.建议在bot目录下使用nb脚手架进行安装

**Comment by A-kirami** [comment]
真寻不是用poetry的虚拟环境吗，确保依赖都有正确安装

**Comment by Siota02** [comment]
> 真寻不是用poetry的虚拟环境吗，确保依赖都有正确安装

 确实，而且真寻有自己的（
