### ISSUE TITLE
[BUG]: asyncio抛出NotImplementedError

### ISSUE THREAD

**Issue by misaka10032w** [A-kirami/nonebot-plugin-chatgpt#63]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

37a43bfe4544935b64769966a4cdf00d605e327b

### 问题描述

使用pip install --upgrade，升级插件，之后抛出异常，尝试卸载插件使用脚手架安装未解决，感觉可能是依赖版本不对？

### 复现步骤

安装插件后报错，屏蔽插件之后nonebot正常启动。

### 预期行为

nonebot正常启动

### 实际行为

nonebot炸了

### 日志信息

`12-14 10:22:16 [INFO] nonebot_plugin_apscheduler | Scheduler Started
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at C:\Users\Administrator\AppData\Local\Progra
ms\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py
", line 247, in run
    await self._transport.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py"
, line 132, in connect
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py"
, line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_s
ubprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1667, in subpro
cess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_s
ubprocess_transport
    raise NotImplementedError
NotImplementedError
12-14 10:22:16 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 671
, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 566
, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 648
, in startup
    await handler()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\__ini
t__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\brows
er.py", line 60, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\brows
er.py", line 36, in init
    _playwright = await async_playwright().start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_m
anager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_m
anager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py"
, line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_s
ubprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1667, in subpro
cess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_s
ubprocess_transport
    raise NotImplementedError
NotImplementedError

12-14 10:22:16 [ERROR] uvicorn | Application startup failed. Exiting.`

### 额外补充
版本信息：
程序：
python V3.10.7
nonebot 2.0.0rc2
nonebot-adapter-cqhttp     2.0.0b1
依赖：
asyncio    3.4.3
playwright    1.28.0
starlette       0.22.0
nonebot_plugin_htmlrender 0.2.0.1
_No response_

**Comment by misaka10032w** [comment]
python不太会用，还请大佬讲解，谢谢啦

**Comment by misaka10032w** [comment]
搞清楚了，.env.dev里面也有fastapi_reload 字段

**Comment by a7a8a9** [comment]
你好，我也有这个问题，请问是怎么解决的
