### ISSUE TITLE
[BUG]: 回滚会话出现错误（AttributeError: 'str' object has no attribute 'user_id'）

### ISSUE THREAD

**Issue by Hikari-Ara** [A-kirami/nonebot-plugin-chatgpt#66]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

nonebot-plugin-chatgpt-0.7.0    Python3.9.13

### 问题描述

在执行回滚对话时报错

### 复现步骤

在会话中执行回滚会话指令

### 预期行为

回滚会话

### 日志信息

12-14 15:32:08 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_chatgpt) failed.
Traceback (most recent call last):
  File "e:\nb2tur\bot_test\Kou\bot.py", line 57, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_chatgpt\__init__.py", line 179, in rollback_conversation
    count=session.count(event)
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_chatgpt\utils.py", line 131, in count
    return self[sid]["conversation_id"].count()
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_chatgpt\utils.py", line 75, in __getitem__
    return super().__getitem__(self.id(event))
  File "C:\Users\Ara\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_chatgpt\utils.py", line 112, in id
    event.group_id if isinstance(event, GroupMessageEvent) else event.user_id
AttributeError: 'str' object has no attribute 'user_id'

### 额外补充

![image](https://user-images.githubusercontent.com/111277717/207533907-09343154-aca0-4ecb-8bf0-4a3d72d368bc.png)
![image](https://user-images.githubusercontent.com/111277717/207534137-45ded9ef-b175-4f9c-941c-5c6f50f852cb.png)
![image](https://user-images.githubusercontent.com/111277717/207534192-c5fb3f18-4e48-41de-a28d-81ee8f74a7ae.png)

**Comment by A-kirami** [comment]
@sena-nana 召唤术

**Comment by sena-nana** [comment]
似乎是漏掉了一个commit，我开个pr补上

**Comment by Hikari-Ara** [comment]
> 似乎是漏掉了一个commit，我开个pr补上

保存会话也用不了

**Comment by Hikari-Ara** [comment]
> > > 似乎是漏掉了一个commit，我开个pr补上
> > 
> > 
> > 保存会话也用不了
> 
> 在一起的

好的🤞

**Comment by A-kirami** [comment]
已修复
