### ISSUE TITLE
[BUG]: 请求 ChatGPT 服务器时出现问题

### ISSUE THREAD

**Issue by kotoritan** [A-kirami/nonebot-plugin-chatgpt#80]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.7.2

### 问题描述

ubuntu22.04，香港腾讯云

向bot发起对话，提示：请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: AttributeError: 'NoneType' object has no attribute 'new_page'
![Snipaste_2022-12-16_15-01-37](https://user-images.githubusercontent.com/107339152/208041329-04564fb1-71c6-4a1c-a7fa-ec89450a6e1b.png)

主要报了以下两条错误：

第一条提示未安装playwright，但是我确实已经安装了

![Snipaste_2022-12-16_14-49-33](https://user-images.githubusercontent.com/107339152/208040766-c9c55cd6-720b-4e2f-8313-261a33bbde04.png)

另外一条如下，与bot返回的信息相同

![Snipaste_2022-12-16_14-50-08](https://user-images.githubusercontent.com/107339152/208040984-ac5aa976-15df-4c8a-acf3-7af92812b893.png)
![Snipaste_2022-12-16_14-50-36](https://user-images.githubusercontent.com/107339152/208041021-3aadc042-77c1-4305-889e-afd2d565f260.png)

### 复现步骤

1.启动bot
2.向bot发送消息

### 预期行为

正常回复

### 实际行为

请求服务器出现问题

### 日志信息

12-16 14:44:58 [ERROR] nonebot_plugin_chatgpt | playwright未安装，请先在shell中运行playwright install
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.10/dist-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_chatgpt/__init__.py", line 57, in ai_chat
    await chat_bot.playwright_start()
> File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_chatgpt/chatgpt.py", line 55, in playwright_start
    self.browser = await playwright.firefox.launch(
  File "/usr/local/lib/python3.10/dist-packages/playwright/async_api/_generated.py", line 12809, in launch
    await self._impl_obj.launch(
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/firefox-1364/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-V2g2IG -juggler-pipe -silent
<launched> pid=1102855
[pid=1102855][err] Running Nightly as root in a regular user's session is not supported.  ($XDG_RUNTIME_DIR is /run/user/1000 which is owned by ubuntu.)
[pid=1102855] <process did exit: exitCode=1, signal=null>
[pid=1102855] starting temporary directories cleanup
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1364/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-V2g2IG -juggler-pipe -silent
<launched> pid=1102855
[pid=1102855][err] Running Nightly as root in a regular user's session is not supported.  ($XDG_RUNTIME_DIR is /run/user/1000 which is owned by ubuntu.)
[pid=1102855] <process did exit: exitCode=1, signal=null>
[pid=1102855] starting temporary directories cleanup
============================================================
12-16 14:44:58 [ERROR] nonebot_plugin_chatgpt | ChatGPT request failed: AttributeError: 'NoneType' object has no attribute 'new_page'
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.10/dist-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_chatgpt/__init__.py", line 63, in ai_chat
    msg = await chat_bot(**session[event]).get_chat_response(text)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_chatgpt/chatgpt.py", line 123, in get_chat_response
    async with self.get_page() as page:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_chatgpt/chatgpt.py", line 115, in get_page
    page = await self.content.new_page()
AttributeError: 'NoneType' object has no attribute 'new_page'

**Comment by sena-nana** [comment]
是不是没有执行过playwright install

**Comment by kotoritan** [comment]
> 是不是没有执行过playwright install

确实执行过了。。。输入 playwright -V 也可以查询到安装的版本是最新版的1.28

**Comment by FlashKiana** [comment]
如果你使用了poetry

需要使用      poetry run playwright install

**Comment by mawMOBai** [comment]
请问是否兼容nonebot2，我用的是nonebot2，也出现了同样问题

**Comment by sena-nana** [comment]
> 请问是否兼容nonebot2，我用的是nonebot2，也出现了同样问题

playwright install

**Comment by mawMOBai** [comment]
用了，poetry命令py3.9环境下安装的，playwright -V也能查询到4.28版本安装，但是运行以后它提示未安装

**Comment by sena-nana** [comment]
> 用了，poetry命令py3.9环境下安装的，playwright -V也能查询到4.28版本安装，但是运行以后它提示未安装

poetry 使用poetry run playwright install

**Comment by mawMOBai** [comment]
所以我说了，用了啊，不用poetry run也装不上啊。。。。

**Comment by sena-nana** [comment]
> 所以我说了，用了啊，不用poetry run也装不上啊。。。。

那就看看第一次运行时报错在哪里找不到，然后看看playwright install哪去了，自己改一下文件夹名，或者复制粘贴一下

**Comment by mawMOBai** [comment]
`12-20 23:21:43 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_chatgpt.utils)
12-20 23:21:44 [ERROR] nonebot_plugin_chatgpt | playwright未安装，请先在shell中运行playwright install
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot_plugin_chatgpt/__init__.py", line 57, in ai_chat
    await chat_bot.playwright_start()
> File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 55, in playwright_start
    self.browser = await playwright.firefox.launch(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 12809, in launch
    await self._impl_obj.launch(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/firefox-1364/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-cvPb4j -juggler-pipe -silent
<launched> pid=11829
[pid=11829][err] /root/.cache/ms-playwright/firefox-1364/firefox/firefox: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/.cache/ms-playwright/firefox-1364/firefox/firefox)
[pid=11829][err] /root/.cache/ms-playwright/firefox-1364/firefox/firefox: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/.cache/ms-playwright/firefox-1364/firefox/firefox)
[pid=11829] <process did exit: exitCode=1, signal=null>
[pid=11829] starting temporary directories cleanup
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1364/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-cvPb4j -juggler-pipe -silent
<launched> pid=11829
[pid=11829][err] /root/.cache/ms-playwright/firefox-1364/firefox/firefox: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/.cache/ms-playwright/firefox-1364/firefox/firefox)
[pid=11829][err] /root/.cache/ms-playwright/firefox-1364/firefox/firefox: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/.cache/ms-playwright/firefox-1364/firefox/firefox)
[pid=11829] <process did exit: exitCode=1, signal=null>
[pid=11829] starting temporary directories cleanup
============================================================
12-20 23:21:44 [ERROR] nonebot_plugin_chatgpt | ChatGPT request failed: AttributeError: 'NoneType' object has no attribute 'new_page'
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot_plugin_chatgpt/__init__.py", line 63, in ai_chat
    msg = await chat_bot(**session[event]).get_chat_response(text)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 123, in get_chat_response
    async with self.get_page() as page:
  File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-1l4Lsu0u-py3.9/lib/python3.9/site-packages/nonebot_plugin_chatgpt/chatgpt.py", line 115, in get_page
    page = await self.content.new_page()
AttributeError: 'NoneType' object has no attribute 'new_page'`

我不太会看这个，麻烦你这边方便的话能帮我看一下么，感谢

**Comment by sena-nana** [comment]
playwright install

**Comment by ilyaw39** [comment]
> playwright install

在执行 `playwright install` 后, 测试在 Ubuntu 22.04/22.10 x64/ Python 10.7 的环境下运行 `playwright install-deps` 时提示安装失败. 使用 apt 手动安装依赖似乎也不能解决问题. 应该是 webkit 的依赖不兼容导致的.

使用 `playwright install-deps chromium firefox` 解决了 `AttributeError: 'NoneType' object has no attribute 'new_page'` 的问题.
