### ISSUE TITLE
[BUG]: 无法刷新session

### ISSUE THREAD

**Issue by cvb011** [A-kirami/nonebot-plugin-chatgpt#9]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

commit: 73ad1fc

### 问题描述

新版本的chatgpt对消息无响应，后台提示
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
挂在刷新session上
之前类似的问题是通过UA解决的，但是该版本已默认带有UA且尝试手动更改为其它系统UA但问题依旧
使用socks5走新加坡节点

### 复现步骤

100%触发

### 日志信息

  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jason/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 688, in simple_run
    await handler(
  File "/home/jason/.cache/pypoetry/virtualenvs/zhenxun-bot-iiwV9KF4-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/jason/zhenxun_bot/plugins/nonebot_plugin_chatgpt/__init__.py", line 69, in ai_chat
    msg = await chat_bot(**session[session_id]).get_chat_response(text)
  File "/home/jason/zhenxun_bot/plugins/nonebot_plugin_chatgpt/chatgpt.py", line 63, in get_chat_response
    await self.refresh_session()
  File "/home/jason/zhenxun_bot/plugins/nonebot_plugin_chatgpt/chatgpt.py", line 93, in refresh_session
    raise RuntimeError("Error refreshing session") from e
RuntimeError: Error refreshing session

**Comment by satisl** [comment]
这里也差不多，调了好久用户代理，换了几个节点，抓了好多次session都无用

Traceback (most recent call last):
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 91, in refresh_session
    self.authorization = response.json()["accessToken"]
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\httpx\_models.py", line 751, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "D:\stable-diffusion-webui-master\py310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\stable-diffusion-webui-master\py310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\stable-diffusion-webui-master\py310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\stable-diffusion-webui-master\py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\stable-diffusion-webui-master\py310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\stable-diffusion-webui-master\py310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\stable-diffusion-webui-master\py310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\stable-diffusion-webui-master\py310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\stable-diffusion-webui-master\py310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "D:\stable-diffusion-webui-master\py310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot_plugin_chatgpt\__init__.py", line 50, in ai_chat
    msg = await chat_bot(**session[session_id]).get_chat_response(text)
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 63, in get_chat_response
    await self.refresh_session()
  File "D:\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-xh4E3Fh5-py3.10\lib\site-packages\nonebot_plugin_chatgpt\chatgpt.py", line 93, in refresh_session
    raise RuntimeError("Error refreshing session") from e
RuntimeError: Error refreshing session

**Comment by leinlin** [comment]
![image](https://user-images.githubusercontent.com/30318270/205852170-776068d5-6bb5-4adf-bdb9-80f637b14568.png)

**Comment by bridgeL** [comment]
一样，` response = await client.get("https://chat.openai.com/api/auth/session")`

返回的是<Response [403 Forbidden]>

而且我看`__Secure-next-auth.session-token`的值已经在不断变化了，一直跳动

**Comment by wearshoes** [comment]
> 
我试了一下 直接curl是需要加useragent才能不报403的问题

**Comment by wearshoes** [comment]
> ![image](https://user-images.githubusercontent.com/30318270/205852170-776068d5-6bb5-4adf-bdb9-80f637b14568.png)

我试了一下直接curl是需要加useragent才能不报403的错误

**Comment by A-kirami** [comment]
尝试更新到最新版以查看问题是否解决

**Comment by wearshoes** [comment]
更新到最新版后依然获取不到session
![2 MQR5H0 2G)M1Z~4~O5GR0](https://user-images.githubusercontent.com/30278479/205910084-f8e1fc0b-bcbc-4322-9376-ad7d5a91e144.png)

**Comment by A-kirami** [comment]
> 更新到最新版后依然获取不到session ![2 MQR5H0 2G)M1Z4O5GR0](https://user-images.githubusercontent.com/30278479/205910084-f8e1fc0b-bcbc-4322-9376-ad7d5a91e144.png) 我试过直接使用curl 走代理访问 chat.openai.com/api/auth/session了 没加token去访问但是也有一个空{}的返回值

这个错误信息和上面那些不一样，可以另开一个 issue。

**Comment by Jerry-FaGe** [comment]
> > 更新到最新版后依然获取不到session ![2 MQR5H0 2G)M1Z4O5GR0](https://user-images.githubusercontent.com/30278479/205910084-f8e1fc0b-bcbc-4322-9376-ad7d5a91e144.png) 我试过直接使用curl 走代理访问 chat.openai.com/api/auth/session了 没加token去访问但是也有一个空{}的返回值
> 
> 这个错误信息和上面那些不一样，可以另开一个 issue。

我跟这位的报错差不多，稳定复现
![image](https://user-images.githubusercontent.com/40235071/205947211-76f08324-147b-495e-b97c-825f281216c1.png)

**Comment by cvb011** [comment]
我刚刚看了下其他的类似项目，其都需要一个额外的 openai 的 APIKey 但是在本项目中没有，有没有可能是这个原因导致的报错？

**Comment by A-kirami** [comment]
> 我刚刚看了下其他的类似项目，其都需要一个额外的 openai 的 APIKey 但是在本项目中没有，有没有可能是这个原因导致的报错？

我在 [acheong08/ChatGPT](https://github.com/acheong08/ChatGPT) 中没有看到额外的 APIKey 要求，这也许不是必要的？

**Comment by cvb011** [comment]
> > 我刚刚看了下其他的类似项目，其都需要一个额外的 openai 的 APIKey 但是在本项目中没有，有没有可能是这个原因导致的报错？
> 
> 我在 [acheong08/ChatGPT](https://github.com/acheong08/ChatGPT) 中没有看到额外的 APIKey 要求，这也许不是必要的？

但是类似的机器人项目
[kifuan/nonebot-plugin-gpt](https://github.com/kifuan/nonebot-plugin-gpt)中是需要的，似乎是因为请求的方式不同？不过今天插件是可以正常刷新session的，如果明天也未出现此问题，我就关闭此issue了

**Comment by cvb011** [comment]
由于持续两日未出现类似报错，关闭此issue
