### ISSUE TITLE
[BUG]: 插件加载成功但uvicorn启动失败导致退出

### ISSUE THREAD

**Issue by KiDisplayBlueScreen** [A-kirami/nonebot-plugin-chatgpt#90]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.7.3

### 问题描述

如标题所示, 如不加载本插件则可成功启动机器人

### 复现步骤

启动时出错

### 预期行为

正常启动

### 实际行为

启动失败

### 日志信息

12-19 10:19:30 [SUCCESS] nonebot | Succeeded to import "YetAnotherPicSearch"
12-19 10:19:31 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
12-19 10:19:31 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
12-19 10:19:31 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_chatgpt"
12-19 10:19:32 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_kawaii_robot"
12-19 10:19:33 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
12-19 10:19:33 [SUCCESS] nonebot | Succeeded to import "ELF_RSS2"
12-19 10:19:33 [INFO] uvicorn | Started server process [520]
12-19 10:19:33 [INFO] uvicorn | Waiting for application startup.
12-19 10:19:33 [INFO] nonebot_plugin_apscheduler | Scheduler Started
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
12-19 10:19:33 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 60, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 36, in init
    _playwright = await async_playwright().start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

12-19 10:19:33 [ERROR] uvicorn | Application startup failed. Exiting.
12-19 10:19:49 [INFO] uvicorn | Stopping reloader process [8640]

### 额外补充

也许和ELF_RSS2插件有关 它要求的nonebot_plugin_apscheduler版本是0.1.4 本插件要求的是0.2.0(虽然一般会向上兼容

**Comment by A-kirami** [comment]
![image](https://user-images.githubusercontent.com/66513481/208379749-dd8d574c-c2a7-4bd2-92df-81c965f95b38.png)
